/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PrestasiRouteImport } from './routes/prestasi'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as BeritaRouteImport } from './routes/berita'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminPrestasiRouteImport } from './routes/_authenticated/admin/prestasi'
import { Route as AuthenticatedAdminPengumumanRouteImport } from './routes/_authenticated/admin/pengumuman'
import { Route as AuthenticatedAdminGaleriRouteImport } from './routes/_authenticated/admin/galeri'
import { Route as AuthenticatedAdminBeritaRouteImport } from './routes/_authenticated/admin/berita'
import { Route as AuthenticatedAdminAgendaRouteImport } from './routes/_authenticated/admin/agenda'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestasiRoute = PrestasiRouteImport.update({
  id: '/prestasi',
  path: '/prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaRoute = BeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPrestasiRoute =
  AuthenticatedAdminPrestasiRouteImport.update({
    id: '/prestasi',
    path: '/prestasi',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPengumumanRoute =
  AuthenticatedAdminPengumumanRouteImport.update({
    id: '/pengumuman',
    path: '/pengumuman',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGaleriRoute =
  AuthenticatedAdminGaleriRouteImport.update({
    id: '/galeri',
    path: '/galeri',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBeritaRoute =
  AuthenticatedAdminBeritaRouteImport.update({
    id: '/berita',
    path: '/berita',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAgendaRoute =
  AuthenticatedAdminAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/berita': typeof BeritaRoute
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/prestasi': typeof PrestasiRoute
  '/profil': typeof ProfilRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/berita': typeof AuthenticatedAdminBeritaRoute
  '/admin/galeri': typeof AuthenticatedAdminGaleriRoute
  '/admin/pengumuman': typeof AuthenticatedAdminPengumumanRoute
  '/admin/prestasi': typeof AuthenticatedAdminPrestasiRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/berita': typeof BeritaRoute
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/prestasi': typeof PrestasiRoute
  '/profil': typeof ProfilRoute
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/berita': typeof AuthenticatedAdminBeritaRoute
  '/admin/galeri': typeof AuthenticatedAdminGaleriRoute
  '/admin/pengumuman': typeof AuthenticatedAdminPengumumanRoute
  '/admin/prestasi': typeof AuthenticatedAdminPrestasiRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/berita': typeof BeritaRoute
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/prestasi': typeof PrestasiRoute
  '/profil': typeof ProfilRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/_authenticated/admin/berita': typeof AuthenticatedAdminBeritaRoute
  '/_authenticated/admin/galeri': typeof AuthenticatedAdminGaleriRoute
  '/_authenticated/admin/pengumuman': typeof AuthenticatedAdminPengumumanRoute
  '/_authenticated/admin/prestasi': typeof AuthenticatedAdminPrestasiRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/berita'
    | '/galeri'
    | '/kontak'
    | '/prestasi'
    | '/profil'
    | '/admin'
    | '/admin/agenda'
    | '/admin/berita'
    | '/admin/galeri'
    | '/admin/pengumuman'
    | '/admin/prestasi'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/berita'
    | '/galeri'
    | '/kontak'
    | '/prestasi'
    | '/profil'
    | '/admin/agenda'
    | '/admin/berita'
    | '/admin/galeri'
    | '/admin/pengumuman'
    | '/admin/prestasi'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agenda'
    | '/auth'
    | '/berita'
    | '/galeri'
    | '/kontak'
    | '/prestasi'
    | '/profil'
    | '/_authenticated/admin'
    | '/_authenticated/admin/agenda'
    | '/_authenticated/admin/berita'
    | '/_authenticated/admin/galeri'
    | '/_authenticated/admin/pengumuman'
    | '/_authenticated/admin/prestasi'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  BeritaRoute: typeof BeritaRoute
  GaleriRoute: typeof GaleriRoute
  KontakRoute: typeof KontakRoute
  PrestasiRoute: typeof PrestasiRoute
  ProfilRoute: typeof ProfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestasi': {
      id: '/prestasi'
      path: '/prestasi'
      fullPath: '/prestasi'
      preLoaderRoute: typeof PrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita': {
      id: '/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/prestasi': {
      id: '/_authenticated/admin/prestasi'
      path: '/prestasi'
      fullPath: '/admin/prestasi'
      preLoaderRoute: typeof AuthenticatedAdminPrestasiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pengumuman': {
      id: '/_authenticated/admin/pengumuman'
      path: '/pengumuman'
      fullPath: '/admin/pengumuman'
      preLoaderRoute: typeof AuthenticatedAdminPengumumanRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/galeri': {
      id: '/_authenticated/admin/galeri'
      path: '/galeri'
      fullPath: '/admin/galeri'
      preLoaderRoute: typeof AuthenticatedAdminGaleriRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/berita': {
      id: '/_authenticated/admin/berita'
      path: '/berita'
      fullPath: '/admin/berita'
      preLoaderRoute: typeof AuthenticatedAdminBeritaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/agenda': {
      id: '/_authenticated/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AuthenticatedAdminAgendaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAgendaRoute: typeof AuthenticatedAdminAgendaRoute
  AuthenticatedAdminBeritaRoute: typeof AuthenticatedAdminBeritaRoute
  AuthenticatedAdminGaleriRoute: typeof AuthenticatedAdminGaleriRoute
  AuthenticatedAdminPengumumanRoute: typeof AuthenticatedAdminPengumumanRoute
  AuthenticatedAdminPrestasiRoute: typeof AuthenticatedAdminPrestasiRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAgendaRoute: AuthenticatedAdminAgendaRoute,
    AuthenticatedAdminBeritaRoute: AuthenticatedAdminBeritaRoute,
    AuthenticatedAdminGaleriRoute: AuthenticatedAdminGaleriRoute,
    AuthenticatedAdminPengumumanRoute: AuthenticatedAdminPengumumanRoute,
    AuthenticatedAdminPrestasiRoute: AuthenticatedAdminPrestasiRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  BeritaRoute: BeritaRoute,
  GaleriRoute: GaleriRoute,
  KontakRoute: KontakRoute,
  PrestasiRoute: PrestasiRoute,
  ProfilRoute: ProfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
